#!/bin/bash
rm -f /root/.ssh/known_hosts
PASSWORD=rtk222

echo "NetS-X Client cleanup script"
echo "Version: 0.1"
echo "Maintainer: Alexander Ott <mail@alexanderott.com>"
echo

#alle pcs
mylist=( 172.20.10.3 172.20.30.21 172.20.40.3 10.0.1.3 172.20.20.131 172.20.30.22 10.0.1.4) #172.20.40.2 (vlan40_pc1)


for TARGET in "${mylist[@]}"; do
/root/client_tools/deploy_helper $PASSWORD $TARGET echo; /usr/bin/systremix_reinstall HACKINGGAME
done
