#!/bin/bash

ADMIN_USER=Student
ADMIN_USER_SMALL=stud
DISTRO=precise
PASSWORD=r00tme
VM_ARCH=amd64

#make vms
#Game engine
ubuntu-vm-builder kvm $DISTRO --hostname GameEngine --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --domain=nets-x -d /home/vms/GameEngine --addpkg ssh vim cron --libvirt qemu:///system --bridge=br0 --bridge=br1 --bridge=extbr2

umount /dev/loop1

#--bridge=br0  --bridge=br1      --network=eth3.2


#client Game Internet
ubuntu-vm-builder kvm $DISTRO --hostname GI_SERVER --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=10.0.8.10  --mask=255.255.255.0 --bcast=10.0.8.255  --gw=10.0.8.20  --dns=10.0.8.20 --domain=gi.nets-x -d /home/vms/GI_SERVER --addpkg ssh vim cron --libvirt qemu:///system --bridge=br1

umount /dev/loop1

#clients DMZ
ubuntu-vm-builder kvm $DISTRO --hostname DMZ_SSERVER --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=10.0.1.3  --mask=255.255.255.0 --bcast=10.0.1.255  --gw=10.0.1.2   --dns=10.0.1.2 --domain=dmz.nets-x -d /home/vms/DMZ_SSERVER --addpkg ssh vim cron --libvirt qemu:///system --bridge=br2

umount /dev/loop1

ubuntu-vm-builder kvm $DISTRO --hostname DMZ_HONEYD --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=10.0.1.4  --mask=255.255.255.0 --bcast=10.0.1.255  --gw=10.0.1.2   --dns=10.0.1.2 --domain=dmz.nets-x -d /home/vms/DMZ_HONEYD --addpkg ssh vim cron --libvirt qemu:///system --bridge=br2

umount /dev/loop1

#CLIENTS VLAN2
ubuntu-vm-builder kvm $DISTRO --hostname Zeus --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.10.3  --mask=255.255.255.0 --bcast=172.20.10.255  --gw=172.20.10.1   --dns=10.0.1.2 --domain=vlan2.nets-x -d /home/vms/ZEUS --addpkg ssh vim cron --libvirt qemu:///system --network=extbr2

umount /dev/loop1

#CLIENTS VLAN3
ubuntu-vm-builder kvm $DISTRO --hostname Ramses --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.20.131  --mask=255.255.255.0 --bcast=172.20.20.255  --gw=172.20.20.1   --dns=10.0.1.2 --domain=vlan3.nets-x -d /home/vms/RAMSES --addpkg ssh vim cron --libvirt qemu:///system --network=extbr3

umount /dev/loop1

ubuntu-vm-builder kvm $DISTRO --hostname Cleopatra --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.20.132  --mask=255.255.255.0 --bcast=172.20.20.255  --gw=172.20.20.1   --dns=10.0.1.2 --domain=vlan3.nets-x -d /home/vms/CLEOPATRA --addpkg ssh vim cron --libvirt qemu:///system --network=extbr3

umount /dev/loop1

#CLIENTS VLAN4
ubuntu-vm-builder kvm $DISTRO --hostname Pluto --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.30.21  --mask=255.255.255.0 --bcast=172.20.30.255  --gw=172.20.30.1   --dns=10.0.1.2 --domain=vlan4.nets-x -d /home/vms/PLUTO --addpkg ssh vim cron --libvirt qemu:///system --network=extbr4

umount /dev/loop1

ubuntu-vm-builder kvm $DISTRO --hostname Venus --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.30.22  --mask=255.255.255.0 --bcast=172.20.30.255  --gw=172.20.30.1   --dns=10.0.1.2 --domain=vlan4.nets-x -d /home/vms/VENUS --addpkg ssh vim cron --libvirt qemu:///system --network=extbr4

umount /dev/loop1

#CLIENTS VLAN5
ubuntu-vm-builder kvm $DISTRO --hostname Server --user $ADMIN_USER_SMALL --name=$ADMIN_USER --pass $PASSWORD -a $VM_ARCH --install-mirror=http://127.0.0.1:3142/de.archive.ubuntu.com/ubuntu --mirror http://10.0.8.20:3142/de.archive.ubuntu.com/ubuntu --components main,restricted,multiverse,universe  --ip=172.20.40.2  --mask=255.255.255.0 --bcast=172.20.40.255  --gw=172.20.40.1   --dns=10.0.1.2 --domain=vlan5.nets-x -d /home/vms/SERVER --addpkg ssh vim cron --libvirt qemu:///system --network=extbr5
